### ISSUE TITLE
Clicking "next stage" does not increase progress

### ISSUE THREAD

**Issue by kumobb** [q815101630/LeetFlash#18]
Hi,

I have been using the app for a quite while now and its great. However there seems to be a bug where just clicking "next stage" on the daily review page does not increase the review stage. It only lets the problem show up on the next review date but the problem's review stage is not changed. Only by resubmitting the question on leetcode can the progress bar be increased.

Example:
<img width="1100" alt="Snipaste_2022-09-15_17-26-32" src="https://user-images.githubusercontent.com/56459571/190531235-478339c1-d845-441b-a083-460371294880.png">
These questions were all firstly submitted on 13th and are supposed to be reviewd on 15th.
For question 1568, I just clicked "next stage". Then it will show up again on 20th, 5 days later. However the progress bar stays the same, which means if I click "next stage" on 20th, it will again show up 5 days later (25th). So this problem will never gets archived  and will keep showing up.
The next 2 questions were resubmitted to leetcode. They are both to be reviewd on 20th and their progress bars are correctly incremented.

I do not know if this is intentionally designed or a bug. If it is a bug, I would greatly appreciate it if it can be fixed.

Thank you

**Comment by lucheng-hugh** [comment]
This seems like a bug. For now, if you want to archive some questions, you can archive them with the `multi-archive` option.
Thanks for reporting.

**Comment by lucheng-hugh** [comment]
fixed in the latest update
