### ISSUE TITLE
syntax error on popup preview

### ISSUE THREAD

**Issue by ghost** [q815101630/LeetFlash#7]
![popup](https://user-images.githubusercontent.com/98380608/180391366-9835d196-5216-463b-87c5-c75a99ee656e.png)
Seem like there is a problem with the markdown

**Comment by Toubat** [comment]
The issue is because we use an external library to parse html text into markdown format. However, it seems the third-party library has some parsing issue. I will try to fix this ASAP.

**Comment by lucheng-hugh** [comment]
Resolved 63802820eadd46caee8bf584763be9e5bbd0120a
